---
deployment:
  tasks:
    - export DEPLOYPATH=/home/igrej478/public_html
    - /usr/local/bin/npm ci --only=production
    - /usr/local/bin/npm run build
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/rm -rf dist
